import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Rizzlord",
  description:
    "The terms that govern your use of the Rizzlord AI Wingman app, including subscription, free trial, and auto-renewal terms.",
  robots: { index: true, follow: true },
};

export default function TermsOfService() {
  return (
    <main className="legal-shell">
      <header className="legal-header">
        <h1 className="legal-title">Terms of Service</h1>
        <p className="legal-meta">Effective date: May 21, 2026</p>
      </header>

      <section className="legal-section">
        <h2>1. Acceptance of these Terms</h2>
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) form a binding contract between you and{" "}
          <strong>[LEGAL ENTITY NAME]</strong> (&ldquo;Rizzlord,&rdquo; &ldquo;we,&rdquo;
          &ldquo;us,&rdquo; or &ldquo;our&rdquo;). They govern your access to and use of the
          Rizzlord mobile application, our website at rizzlord.app, and any related services
          (together, the &ldquo;Service&rdquo;).
        </p>
        <p>
          By downloading, installing, accessing, or using the Service, you confirm that you have
          read, understood, and agreed to these Terms and to our{" "}
          <Link href="/privacy">Privacy Policy</Link>. If you do not agree, do not use the
          Service.
        </p>
      </section>

      <section className="legal-section">
        <h2>2. Eligibility</h2>
        <p>
          The Service is intended for users <strong>17 years of age or older</strong>. By using
          the Service you represent and warrant that you are at least 17 years old, that you have
          the legal capacity to enter into a binding contract in your jurisdiction, and that you
          are not barred from using the Service under applicable law.
        </p>
        <p>
          Some jurisdictions set a higher age of digital consent. If you live in such a
          jurisdiction, you must meet that higher age. If you are using the Service on behalf of
          an organization, you represent that you have authority to bind that organization to
          these Terms.
        </p>
      </section>

      <section className="legal-section">
        <h2>3. Description of the Service</h2>
        <p>
          Rizzlord is an AI-powered &ldquo;wingman&rdquo; that generates pickup lines, openers,
          replies, and other conversation suggestions based on the context you provide. You give
          Rizzlord a snippet of a chat, a profile bio, a screenshot, or a short description, and
          the Service returns AI-generated text intended to help you respond, flirt, or start a
          conversation.
        </p>
        <p>
          Suggestions are generated by machine learning models. They are <em>suggestions only</em>{" "}
          and may be inaccurate, off-tone, awkward, factually wrong, biased, or otherwise
          unsuitable for any particular situation. You are solely responsible for reviewing every
          suggestion and for any message you choose to send to a third party. Rizzlord is a tool,
          not a substitute for your judgment.
        </p>
      </section>

      <section className="legal-section">
        <h2>4. Accounts</h2>
        <p>
          You may be required to create an account or sign in with a third-party identity provider
          to use parts of the Service. You agree to provide accurate, current, and complete
          information when registering and to keep that information up to date. One account per
          person.
        </p>
        <p>
          You are responsible for safeguarding your login credentials and for all activity that
          occurs under your account. Notify us immediately at{" "}
          <a href="mailto:[contact email]">[contact email]</a> if you suspect any unauthorized
          access. We are not liable for losses caused by unauthorized use of your account that
          results from your failure to keep credentials secure.
        </p>
        <p>
          You may close your account at any time from within the app. Closing your account does
          not automatically cancel an active subscription &mdash; see Section 7.
        </p>
      </section>

      <section className="legal-section">
        <h2>5. Acceptable use</h2>
        <p>
          Rizzlord is built to help people connect. Using it to hurt, deceive, or harass people is
          not allowed, and we will enforce this strictly. You agree that you will not, and will
          not allow any third party to:
        </p>
        <ul>
          <li>
            Use the Service to harass, threaten, stalk, intimidate, defame, or doxx any person.
          </li>
          <li>
            Impersonate any person or organization or misrepresent your affiliation with anyone.
          </li>
          <li>
            Generate, request, solicit, or share any sexual content involving minors, or any
            content that sexualizes minors in any way. This prohibition is absolute and we will
            report such activity to law enforcement where required.
          </li>
          <li>
            Use the Service to commit romance scams, &ldquo;catfish&rdquo; people for material
            gain, fraudulently induce someone into a relationship or transaction, or otherwise
            defraud others.
          </li>
          <li>
            Use Outputs to discriminate against any person on the basis of race, ethnicity,
            religion, national origin, sex, gender identity, sexual orientation, disability, age,
            or any other protected characteristic.
          </li>
          <li>
            Submit other people&rsquo;s private communications, photos, or personal information
            without their consent.
          </li>
          <li>
            Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source
            code, model weights, system prompts, or training data behind the Service, except to
            the limited extent that applicable law expressly permits.
          </li>
          <li>
            Use bots, scrapers, or other automated means to access the Service or to generate
            Outputs in bulk; use the Service to build or train a competing AI product or service;
            or resell Outputs.
          </li>
          <li>
            Probe, scan, or test the vulnerability of the Service; circumvent any rate limits,
            authentication, or security measures; or interfere with or disrupt the Service or any
            servers or networks connected to it.
          </li>
          <li>
            Use the Service in violation of any applicable law, regulation, or third-party right.
          </li>
        </ul>
        <p>
          We may investigate and respond to suspected violations, including by suspending or
          terminating accounts and cooperating with law enforcement.
        </p>
      </section>

      <section className="legal-section">
        <h2>6. Your Content and the license you grant us</h2>
        <p>
          You retain ownership of any text, screenshots, descriptions, or other material you
          submit to the Service (&ldquo;Your Content&rdquo;). You represent and warrant that you
          have all rights necessary to submit Your Content and that doing so does not violate any
          law or any third party&rsquo;s rights.
        </p>
        <p>
          To operate the Service we need permission to use Your Content. You grant Rizzlord a
          worldwide, non-exclusive, royalty-free, sublicensable license to host, store, reproduce,
          transmit, display, modify (for formatting and prompt-construction purposes), and create
          derivative works from Your Content solely to operate, provide, secure, and improve the
          Service &mdash; including by transmitting Your Content to third-party AI model providers
          for inference. This license ends when Your Content is deleted from our active systems,
          except for backups and de-identified data as described in our Privacy Policy.
        </p>
        <p>
          Outputs generated by the Service are provided to you under a limited, personal,
          non-exclusive, non-transferable license to use them for lawful purposes. Because Outputs
          are produced by statistical models, similar or identical Outputs may be generated for
          other users, and we make no guarantee of uniqueness, originality, or ownership of any
          particular Output.
        </p>
      </section>

      <section className="legal-section">
        <h2>7. Subscriptions, free trial, and auto-renewal</h2>
        <p>
          Rizzlord offers <strong>weekly</strong> and <strong>monthly</strong> auto-renewing
          subscriptions. The current price, billing period, and any introductory or promotional
          terms are displayed in the app at the point of purchase and may change for future
          billing periods with notice.
        </p>
        <p>
          <strong>3-day free trial.</strong> Eligible new subscribers may be offered a free trial
          of approximately three (3) days. At the end of the free trial your subscription will{" "}
          <strong>automatically convert to a paid subscription</strong> at the then-current price
          for the plan you selected, unless you cancel at least <strong>24 hours</strong> before
          the trial ends. Free trials are limited to one per user / Apple ID / Google account /
          household as determined by Apple or Google. Any unused portion of a free trial is
          forfeited when you purchase a paid subscription.
        </p>
        <p>
          <strong>Billing.</strong> Payment is charged to your Apple ID or Google Play account at
          confirmation of purchase (or at the end of a free trial). Apple and Google process all
          payments and we do not receive or store your full payment details.
        </p>
        <p>
          <strong>Automatic renewal.</strong> Subscriptions{" "}
          <strong>automatically renew</strong> for the same billing period at the then-current
          price unless auto-renewal is turned off at least 24 hours before the end of the current
          period. Your account will be charged for renewal within 24 hours before the end of the
          current period.
        </p>
        <p>
          <strong>How to cancel.</strong> You can manage your subscription and turn off
          auto-renewal at any time. On iOS, open <em>Settings &gt; [your name] &gt; Subscriptions</em>{" "}
          and select Rizzlord. On Android, open the Play Store, tap your profile, then{" "}
          <em>Payments &amp; subscriptions &gt; Subscriptions</em>. <strong>Deleting the app does
          not cancel your subscription.</strong> Cancellation takes effect at the end of the
          current billing period; you keep access until then.
        </p>
      </section>

      <section className="legal-section">
        <h2>8. Refunds</h2>
        <p>
          All purchases of subscriptions and other in-app items are processed by Apple App Store
          or Google Play. Refunds for those purchases are governed by their policies. Rizzlord
          generally cannot directly issue refunds for store purchases. You can request a refund
          through Apple at support.apple.com/HT204084 or through Google at
          support.google.com/googleplay/answer/2479637.
        </p>
        <p>
          If you are a consumer located in the European Union, the United Kingdom, or another
          jurisdiction with mandatory statutory withdrawal rights, those rights apply where
          required by law. By starting to use the Service during any cooling-off period you
          acknowledge that you expressly request immediate performance and, to the extent
          permitted by law, may lose any right of withdrawal once digital content has been
          supplied.
        </p>
      </section>

      <section className="legal-section">
        <h2>9. Intellectual property</h2>
        <p>
          The Service, including the Rizzlord app, website, brand, name, logo, underlying
          software, prompts, and machine learning models, is owned by Rizzlord and protected by
          intellectual property and other laws. Subject to your compliance with these Terms, we
          grant you a limited, personal, non-exclusive, non-transferable, non-sublicensable,
          revocable license to use the Service for your own personal, non-commercial purposes.
        </p>
        <p>
          All rights not expressly granted are reserved. &ldquo;Rizzlord&rdquo; and the Rizzlord
          logo are trademarks of <strong>[LEGAL ENTITY NAME]</strong>. You may not use them
          without our prior written permission.
        </p>
      </section>

      <section className="legal-section">
        <h2>10. Third-party services</h2>
        <p>
          The Service interoperates with third-party services, including the Apple App Store,
          Google Play, AI model providers, analytics providers, and any external app you copy
          Outputs into. Your use of those third-party services is governed by their own terms and
          privacy policies. We are not responsible for them and do not endorse their content.
        </p>
      </section>

      <section className="legal-section">
        <h2>11. AI-generated content disclaimer</h2>
        <p>
          Outputs are generated by machine learning models and may be inaccurate, biased,
          offensive, or inappropriate for any given person or situation. The Service makes{" "}
          <strong>no guarantee</strong> of dating, romantic, sexual, social, or any other outcome
          from using its suggestions. You agree to review each Output before sending it and to
          use your own judgment. Do not use Rizzlord to make important decisions about
          relationships, health, finances, safety, or any other matter that warrants professional
          advice.
        </p>
      </section>

      <section className="legal-section">
        <h2>12. Feedback</h2>
        <p>
          If you send us suggestions, ideas, or other feedback about the Service, you agree that
          we may use it for any purpose without obligation or compensation to you. Feedback is
          provided voluntarily and is not confidential.
        </p>
      </section>

      <section className="legal-section">
        <h2>13. Termination</h2>
        <p>
          We may suspend, restrict, or terminate your access to all or part of the Service at any
          time, with or without notice, if we reasonably believe you have violated these Terms,
          created risk or possible legal exposure for Rizzlord or other users, engaged in fraud or
          abuse, or if we are required to do so by law.
        </p>
        <p>
          You may stop using the Service at any time. If you have an active subscription, please
          also cancel it as described in Section 7. Sections that by their nature should survive
          termination &mdash; including Sections 5 (Acceptable use), 6 (Your Content), 9
          (Intellectual property), 11 (Disclaimer), 14 (Disclaimers of warranties), 15 (Limitation
          of liability), 16 (Indemnification), 17 (Governing law) and 20 (Miscellaneous) &mdash;
          will survive.
        </p>
      </section>

      <section className="legal-section">
        <h2>14. Disclaimers of warranties</h2>
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT
          WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY
          LAW, RIZZLORD DISCLAIMS ALL WARRANTIES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS
          FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, RELIABILITY, AND THAT THE SERVICE
          OR OUTPUTS WILL BE UNINTERRUPTED, ERROR-FREE, OR SUITABLE FOR ANY PARTICULAR
          INTERACTION OR PERSON.
        </p>
        <p>
          Some jurisdictions do not allow the exclusion of certain warranties; in those
          jurisdictions the exclusions above apply to the maximum extent permitted by law.
        </p>
      </section>

      <section className="legal-section">
        <h2>15. Limitation of liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL RIZZLORD, ITS AFFILIATES, OR
          ITS LICENSORS, DIRECTORS, OFFICERS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF
          PROFITS, REVENUES, DATA, GOODWILL, REPUTATION, RELATIONSHIPS, OR OPPORTUNITIES, WHETHER
          ARISING IN CONTRACT, TORT, STATUTE, OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE
          POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED THE
          GREATER OF (A) THE AMOUNTS YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE EVENT
          GIVING RISE TO THE CLAIM, OR (B) <strong>[USD amount, e.g. $50]</strong>.
        </p>
        <p>
          Some jurisdictions do not allow the limitation of liability for certain damages; in
          those jurisdictions our liability is limited to the maximum extent permitted by law.
        </p>
      </section>

      <section className="legal-section">
        <h2>16. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless Rizzlord and its affiliates and their
          respective directors, officers, employees, and agents from and against any claims,
          liabilities, damages, losses, and expenses (including reasonable attorneys&rsquo; fees)
          arising out of or in any way connected with: (a) Your Content; (b) your use or misuse of
          the Service; (c) your violation of these Terms; or (d) your violation of any law or
          third-party right.
        </p>
      </section>

      <section className="legal-section">
        <h2>17. Governing law and dispute resolution</h2>
        <p>
          These Terms are governed by the laws of{" "}
          <strong>[jurisdiction, e.g. State of Delaware, USA]</strong>, without regard to its
          conflict-of-laws principles. Subject to the arbitration provision below (if any) and any
          mandatory consumer rights you have under local law, the courts located in{" "}
          <strong>[venue]</strong> will have exclusive jurisdiction over any dispute arising out
          of or relating to these Terms or the Service.
        </p>
        <p>
          <strong>[Optional arbitration clause &mdash; remove if not desired.]</strong> Any
          dispute, claim, or controversy arising out of or relating to these Terms or the Service
          will be resolved by binding individual arbitration, and you and Rizzlord each waive the
          right to a trial by jury or to participate in a class action. This provision does not
          apply where prohibited by law. You may opt out of arbitration within 30 days of first
          accepting these Terms by emailing us at{" "}
          <a href="mailto:[contact email]">[contact email]</a>.
        </p>
      </section>

      <section className="legal-section">
        <h2>18. Apple-specific terms</h2>
        <p>
          If you obtained the Rizzlord app from the Apple App Store, the following also apply and
          take precedence over any inconsistent provisions of these Terms:
        </p>
        <ul>
          <li>
            These Terms are an agreement between you and Rizzlord only, and not with Apple. Apple
            is not responsible for the app or its content.
          </li>
          <li>
            Your license to use the app is limited to use on Apple-branded products that you own
            or control and as permitted by the Usage Rules in the App Store Terms of Service.
          </li>
          <li>
            Apple has no obligation to provide maintenance or support for the app.
          </li>
          <li>
            In the event of any failure of the app to conform to any applicable warranty, you may
            notify Apple, and Apple will refund the purchase price (if any) for the app to you.
            To the maximum extent permitted by law, Apple has no other warranty obligation with
            respect to the app.
          </li>
          <li>
            Apple is not responsible for addressing any claims by you or any third party relating
            to the app, including product liability, consumer protection, or intellectual
            property claims.
          </li>
          <li>
            You represent that you are not located in a country subject to a U.S. Government
            embargo and that you are not on any U.S. Government list of prohibited or restricted
            parties.
          </li>
          <li>
            Apple and Apple&rsquo;s subsidiaries are third-party beneficiaries of these Terms
            and, upon your acceptance, will have the right to enforce them against you.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>19. Changes to these Terms</h2>
        <p>
          We may update these Terms from time to time as the Service evolves or as law requires.
          When we do, we will update the &ldquo;Effective date&rdquo; at the top of the page and,
          for material changes, give additional notice through the Service. Your continued use of
          the Service after the updated Terms take effect means you accept the changes. If you do
          not agree, you must stop using the Service.
        </p>
      </section>

      <section className="legal-section">
        <h2>20. Miscellaneous</h2>
        <p>
          These Terms, together with the <Link href="/privacy">Privacy Policy</Link> and any other
          terms we reference, are the entire agreement between you and Rizzlord regarding the
          Service and supersede any prior agreements. If any provision of these Terms is found to
          be unenforceable, the remaining provisions will remain in full force and effect. Our
          failure to enforce any right or provision is not a waiver of that right or provision.
          You may not assign or transfer these Terms without our prior written consent; we may
          assign these Terms at any time without notice.
        </p>
      </section>

      <section className="legal-section">
        <h2>21. Contact us</h2>
        <p>
          Questions about these Terms? Reach out at:
        </p>
        <p>
          <strong>[LEGAL ENTITY NAME]</strong>
          <br />
          [Business address]
          <br />
          <a href="mailto:[contact email]">[contact email]</a>
        </p>
      </section>

      <p className="legal-back">
        <Link href="/">← Back to Rizzlord</Link>
      </p>
    </main>
  );
}
